[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-api-url.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-staging-backend-api-url.com"
